services:
  postgres:
    image: postgres:15
    container_name: recess_postgres_dev
    environment:
      POSTGRES_DB: recess_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - recess-network

  backend:
    build: .
    container_name: recess_backend_dev
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/recess_development"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Mount source code for development (optional - remove for production)
      - .:/app
      - /app/node_modules
    networks:
      - recess-network
    # Override for development with hot reload
    command: npm run dev

volumes:
  postgres_data:

networks:
  recess-network:
    driver: bridge