// Mock the database module before importing shareService
jest.mock('../db', () => ({
  db: {}
}));

// Mock the schema module
jest.mock('../db/schema', () => ({
  shares: {},
  users: {},
  workoutTemplates: {},
  templateExercises: {},
  exercises: {},
  workoutPrograms: {},
  programWeeks: {}
}));

import { generateShareToken } from './shareService';
import {
  validateCreateShare,
  validateShareToken,
  isValidUuid,
} from '../utils/validation';

describe('shareService', () => {
  describe('generateShareToken', () => {
    it('should generate a 12-character token', () => {
      const token = generateShareToken();
      expect(token).toHaveLength(12);
    });

    it('should generate URL-safe characters only', () => {
      // Generate many tokens and check they only contain base64url characters
      for (let i = 0; i < 100; i++) {
        const token = generateShareToken();
        expect(token).toMatch(/^[a-zA-Z0-9_-]+$/);
      }
    });

    it('should generate unique tokens across calls', () => {
      const tokens = new Set<string>();
      for (let i = 0; i < 100; i++) {
        tokens.add(generateShareToken());
      }
      // All 100 tokens should be unique (collision with 72 bits is essentially impossible)
      expect(tokens.size).toBe(100);
    });
  });
});

describe('share validation', () => {
  describe('validateCreateShare', () => {
    const validUuid = '12345678-1234-1234-1234-123456789abc';

    it('should accept valid template share input', () => {
      const result = validateCreateShare({
        type: 'template',
        itemId: validUuid
      });

      expect(result.valid).toBe(true);
      expect(result.sanitized?.type).toBe('template');
      expect(result.sanitized?.itemId).toBe(validUuid);
    });

    it('should accept valid program share input', () => {
      const result = validateCreateShare({
        type: 'program',
        itemId: validUuid
      });

      expect(result.valid).toBe(true);
      expect(result.sanitized?.type).toBe('program');
      expect(result.sanitized?.itemId).toBe(validUuid);
    });

    it('should reject missing type', () => {
      const result = validateCreateShare({
        itemId: validUuid
      });

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('type'))).toBe(true);
    });

    it('should reject invalid type', () => {
      const result = validateCreateShare({
        type: 'workout',
        itemId: validUuid
      });

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('type must be one of'))).toBe(true);
    });

    it('should reject missing itemId', () => {
      const result = validateCreateShare({
        type: 'template'
      });

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('itemId'))).toBe(true);
    });

    it('should reject invalid UUID for itemId', () => {
      const result = validateCreateShare({
        type: 'template',
        itemId: 'not-a-uuid'
      });

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('valid UUID'))).toBe(true);
    });

    it('should reject non-object body', () => {
      const result = validateCreateShare('string');
      expect(result.valid).toBe(false);
      expect(result.errors).toContain('Request body must be an object');
    });

    it('should reject null body', () => {
      const result = validateCreateShare(null);
      expect(result.valid).toBe(false);
      expect(result.errors).toContain('Request body must be an object');
    });

    it('should reject numeric type', () => {
      const result = validateCreateShare({
        type: 123,
        itemId: validUuid
      });

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('type'))).toBe(true);
    });

    it('should reject numeric itemId', () => {
      const result = validateCreateShare({
        type: 'template',
        itemId: 12345
      });

      expect(result.valid).toBe(false);
      expect(result.errors.some(e => e.includes('itemId'))).toBe(true);
    });
  });

  describe('validateShareToken', () => {
    it('should accept valid alphanumeric tokens', () => {
      expect(validateShareToken('abc123ABC')).toBe(true);
    });

    it('should accept tokens with hyphens and underscores', () => {
      expect(validateShareToken('abc-123_ABC')).toBe(true);
    });

    it('should accept a 12-character base64url token', () => {
      // Typical token generated by generateShareToken
      expect(validateShareToken('dGVzdHRva2Vu')).toBe(true);
    });

    it('should reject empty string', () => {
      expect(validateShareToken('')).toBe(false);
    });

    it('should reject tokens longer than 64 characters', () => {
      const longToken = 'a'.repeat(65);
      expect(validateShareToken(longToken)).toBe(false);
    });

    it('should accept tokens at exactly 64 characters', () => {
      const maxToken = 'a'.repeat(64);
      expect(validateShareToken(maxToken)).toBe(true);
    });

    it('should reject tokens with special characters', () => {
      expect(validateShareToken('abc!@#')).toBe(false);
      expect(validateShareToken('abc def')).toBe(false);
      expect(validateShareToken('abc/def')).toBe(false);
      expect(validateShareToken('abc+def')).toBe(false);
      expect(validateShareToken('abc=def')).toBe(false);
    });
  });
});
