// R2 Configuration - Change these if switching to a custom domain
export const R2_BASE_URL = 'https://pub-383015826a924878acc220637944c283.r2.dev';
export const BUCKET_PATH = 'recess-fitness-videos';

export function buildVideoUrl(filename: string): string {
  return `${R2_BASE_URL}/${BUCKET_PATH}/${encodeURIComponent(filename)}`;
}

// Valid muscle groups from schema enum
export type MuscleGroup =
  | 'chest' | 'back' | 'shoulders' | 'biceps' | 'triceps'
  | 'quads' | 'hamstrings' | 'glutes' | 'calves' | 'abs'
  | 'forearms' | 'traps' | 'lats';

export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';
export type MovementPattern = 'push' | 'pull' | 'hinge' | 'squat' | 'lunge' | 'carry' | 'rotation' | 'core';
export type ExerciseType = 'compound' | 'isolation' | 'cardio' | 'plyometric' | 'stretch';

export interface ExerciseSeedData {
  name: string;
  videoFilename: string;
  primaryMuscles: MuscleGroup[];
  secondaryMuscles?: MuscleGroup[];
  equipment: string;
  difficulty: DifficultyLevel;
  movementPattern: MovementPattern;
  exerciseType: ExerciseType;
}

export const exerciseSeedData: ExerciseSeedData[] = [
  // === CHEST EXERCISES ===
  {
    name: 'Barbell Bench Press',
    videoFilename: 'Barbell Bench Press_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Dumbbell Chest Bench Press',
    videoFilename: 'Dumbell Chest Bench Press_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Incline Barbell Press',
    videoFilename: 'Incline Barbell Press_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Incline Dumbbell Press',
    videoFilename: 'Incline Dumbell Press_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'DB Chest Fly',
    videoFilename: 'DB Chest Fly_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Machine Chest Press',
    videoFilename: 'Machine Chest Press_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Machine Chest Fly',
    videoFilename: 'Machine Chest Fly_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'One Arm Machine Fly',
    videoFilename: 'One Arm Machine Fly_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Crossover Ladders Chest',
    videoFilename: 'Crossover Ladders Chest_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Smith Machine Chest Press Flat',
    videoFilename: 'Smith Machine Chest Press Flat_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'smith machine',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Smith Machine Incline Chest Press',
    videoFilename: 'Smith Machine Incline Chest Press_1080p.mp4',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'smith machine',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Dips',
    videoFilename: 'Dips_1080p.mp4',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Bench Dips',
    videoFilename: 'Bench Dips_1080p.mp4',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'compound',
  },

  // === BACK EXERCISES ===
  {
    name: 'Deadlift',
    videoFilename: 'Deadlift_1080p.mp4',
    primaryMuscles: ['back', 'hamstrings', 'glutes'],
    secondaryMuscles: ['traps', 'forearms'],
    equipment: 'barbell',
    difficulty: 'advanced',
    movementPattern: 'hinge',
    exerciseType: 'compound',
  },
  {
    name: 'Lat Pulldown',
    videoFilename: 'Lat Pulldown_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Lat Cable Pulldown',
    videoFilename: 'Lat Cable Pulldown_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Close Grip Cable Pulldown',
    videoFilename: 'Close Grip Cable Pulldown_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'One Arm Lat Pulldown',
    videoFilename: 'One Arm Lat Pulldown_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'cable',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Cross-Body Lat Pull-Around',
    videoFilename: 'Cross-Body Lat Pull-Around_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['back'],
    equipment: 'cable',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Chin Up',
    videoFilename: 'Chin Up_1080p.mp4',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['back'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Close Grip Pullup',
    videoFilename: 'Close Grip Pullup_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Wide Grip Pullup',
    videoFilename: 'Wide Grip Pullup_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Machine Pull Up',
    videoFilename: 'Machine Pull Up_1080p.mp4',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Chest-Supported Machine Row',
    videoFilename: 'Chest-Supported Machine Row_1080p.mp4',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Neutral-Grip Seated Cable Row',
    videoFilename: 'Neutral-Grip Seated Cable Row_1080p.mp4',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Wide Grip Seated Cable Row',
    videoFilename: 'Wide Grip Seated Cable Row_1080p.mp4',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Meadows Row',
    videoFilename: 'Meadows Row_1080p.mp4',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Pendlay Deficit Row',
    videoFilename: 'Pendlay Deficit Row_1080p.mp4',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'hamstrings'],
    equipment: 'barbell',
    difficulty: 'advanced',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Smith Machine Back Thing',
    videoFilename: 'Smith Machine Back Thing_1080p.mp4',
    primaryMuscles: ['back'],
    secondaryMuscles: ['lats', 'biceps'],
    equipment: 'smith machine',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'compound',
  },
  {
    name: 'Machine Back Fly',
    videoFilename: 'Machine Back Fly_1080p.mp4',
    primaryMuscles: ['back', 'shoulders'],
    secondaryMuscles: ['traps'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },

  // === SHOULDER EXERCISES ===
  {
    name: 'Dumbbell Shoulder Press',
    videoFilename: 'Dumbell Shoulder Press_1080p.mp4',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Seated DB Shoulder Press',
    videoFilename: 'Seated DB Shoulder Press_1080p.mp4',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'Machine Shoulder Press',
    videoFilename: 'Machine Shoulder Press_1080p.mp4',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'compound',
  },
  {
    name: 'High Cable Lateral Raise',
    videoFilename: 'High Cable Lateral Raise_1080p.mp4',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: '1 Arm 45 Degree Cable Rear Delt Fly',
    videoFilename: '1 Arm 45 Degree Cable Rear Delt Fly_1080p.mp4',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: 'cable',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },

  // === BICEPS EXERCISES ===
  {
    name: 'DB Bicep Curl',
    videoFilename: 'DB Bicep Curl_1080p.mp4',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'EZ Bar Curl',
    videoFilename: 'EZ Bar Curl_1080p.mp4',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Preacher Curl EZ Bar',
    videoFilename: 'Preacher Curl EZ Bar_1080p.mp4',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: 'barbell',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Bayesian Cable Curls',
    videoFilename: 'Bayesian Cable Curls_1080p.mp4',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'intermediate',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Machine Bicep Curl',
    videoFilename: 'Machine Bicep Curl_1080p.mp4',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Standing Hammer Curl',
    videoFilename: 'Standing Hammer Curl_1080p.mp4',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },

  // === TRICEPS EXERCISES ===
  {
    name: 'Tricep Pulldown',
    videoFilename: 'Tricep Pulldown_1080p.mp4',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Tricep Kickback',
    videoFilename: 'Tricep Kickback_1080p.mp4',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Skull Crusher',
    videoFilename: 'Skull Crusher_1080p.mp4',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Dumbbell Skull Crusher',
    videoFilename: 'Dumbell Skull Crusher_1080p.mp4',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Overhead Extensions',
    videoFilename: 'Overhead extensions_1080p.mp4',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },

  // === LEG EXERCISES ===
  {
    name: 'Barbell Squats',
    videoFilename: 'Barbell Squats_1080p.mp4',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'squat',
    exerciseType: 'compound',
  },
  {
    name: 'Smith Machine Squat',
    videoFilename: 'Smith Machine Squat_1080p.mp4',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'smith machine',
    difficulty: 'beginner',
    movementPattern: 'squat',
    exerciseType: 'compound',
  },
  {
    name: 'Leg Press',
    videoFilename: 'Leg Press_1080p.mp4',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'squat',
    exerciseType: 'compound',
  },
  {
    name: 'Dumbbell Lunge',
    videoFilename: 'Dumbell Lunge_1080p.mp4',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'lunge',
    exerciseType: 'compound',
  },
  {
    name: 'Smith Machine Lunge',
    videoFilename: 'Smith Machine Lunge_1080p.mp4',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'smith machine',
    difficulty: 'beginner',
    movementPattern: 'lunge',
    exerciseType: 'compound',
  },
  {
    name: 'DB Bulgarian Split Squat',
    videoFilename: 'DB Bulgarian Split Squat_1080p.mp4',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'lunge',
    exerciseType: 'compound',
  },
  {
    name: 'Lying Leg Curl',
    videoFilename: 'Lying Leg Curl_1080p.mp4',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Seated Leg Curl',
    videoFilename: 'Seated Leg Curl_1080p.mp4',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Calf Raises',
    videoFilename: 'Calf Raises_1080p.mp4',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'push',
    exerciseType: 'isolation',
  },
  {
    name: 'Machine Hip Abduction',
    videoFilename: 'Machine Hip abduction_1080p.mp4',
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'core',
    exerciseType: 'isolation',
  },
  {
    name: 'Machine Hip Adduction',
    videoFilename: 'Machine Hip-Adduction_1080p.mp4',
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'core',
    exerciseType: 'isolation',
  },

  // === TRAPS EXERCISES ===
  {
    name: 'Dumbbell Shoulder Shrug',
    videoFilename: 'Dumbell Shoulder Shrug_1080p.mp4',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Shrug with Bar',
    videoFilename: 'Shrug with bar_1080p.mp4',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'barbell',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },
  {
    name: 'Shrug Machine',
    videoFilename: 'Shrug Machine_1080p.mp4',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'pull',
    exerciseType: 'isolation',
  },

  // === ABS EXERCISES ===
  {
    name: 'Leg Raises',
    videoFilename: 'Leg Raises_1080p.mp4',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'core',
    exerciseType: 'isolation',
  },
];
